### PR TITLE
Manage layered dynamic bundle configurations

### PR DESCRIPTION
**Pull request by christophermaier**
Overview:

```sh
$ cogctl dynamic-config pingdom
LAYER
base
room/ops
user/chris

$ cogctl dynamic-config info pingdom base
{
  "PINGDOM_USER_PASSWORD": "secret_dont_tell",
  "PINGDOM_USER_EMAIL": "cog@operable.io",
  "PINGDOM_APPLICATION_KEY": "blahblahblah"
}

$ cogctl dynamic-config info pingdom
{
  "PINGDOM_USER_PASSWORD": "secret_dont_tell",
  "PINGDOM_USER_EMAIL": "cog@operable.io",
  "PINGDOM_APPLICATION_KEY": "blahblahblah"
}

$ cogctl dynamic-config info pingdom room/ops
{
  "PINGDOM_USER_PASSWORD": "ops4life",
  "PINGDOM_USER_EMAIL": "cog_ops@operable.io",
  "PINGDOM_APPLICATION_KEY": "opsblahblahblah"
}

$ cogctl dynamic-config create pingdom ~/path/to/pingdom/config.yaml --layer=base
Base dynamic config layer for bundle 'pingdom' saved successfully

$ cogctl dynamic-config create pingdom ~/path/to/pingdom/config.yaml
Base dynamic config layer for bundle 'pingdom' saved successfully

$ cogctl dynamic-config create pingdom ~/path/to/pingdom/room_ops.yaml --layer=room/ops
room/ops dynamic config layer for bundle 'pingdom' saved successfully

$ cogctl dynamic-config delete pingdom
Base dynamic config layer for bundle 'pingdom' deleted successfully

$ cogctl dynamic-config delete pingdom room/ops
room/ops dynamic config layer for bundle 'pingdom' deleted successfully
```

Note that the previous `--bundle` option is now an argument, as it is
always required.

### CODE REVIEW

**Comment by kevsmith** [comment]
Would it be better to promote showing the merged config as the default and demote listing layers to an explicit command? I'm torn.

Another thought is it'd be nice to allow the user to view the dynamic config for a given room and (optionally) user like so:

``` shell
$cogctl dynamic-config info pingdom --room=ops --user=chris
{
  "PINGDOM_USER_PASSWORD": "ops4life",
  "PINGDOM_USER_EMAIL": "cog_ops@operable.io",
  "PINGDOM_APPLICATION_KEY": "opsblahblahblah"
}
```

Aside from the above functionality comments, LGTM!

**Comment by christophermaier** [comment]
That  could be useful, but I think it'd need to be a separate command. All the ones here are geared toward management of the individual layers. Plus, to get a merged config you'd _have_ to specify the room and user.

**Comment by christophermaier** [comment]
Might even want that to be a specific endpoint on the API...

**Comment by kevsmith** [comment]
To get a final merged config you are correct. But if I'm an admin trying to debug config funkiness I might want to apply layers one at a time too.

Making the functionality a separate command is fine w/me. Agree re: endpoint. I wasn't trying to specify implementation in my original suggestion :)

**Comment by christophermaier** [comment]
We're going to tackle the aforementioned "effective config" functionality in a separate PR.

**Pull request merged**
