### PR TITLE
Support bulk un/assignments to relay-groups

### PR DESCRIPTION
**Pull request by mpeck**
Changes to relay-groups to allow for multiple bundle assignments.

The syntax is now:
`cogctl relay-groups assign mygroup bundle1 bundle2 bundle3`
`cogctl relay-groups unassign mygroup bundle1 bundle2 bundle3`

depends on https://github.com/operable/cog-api-client/pull/89
resolves https://github.com/operable/cog/issues/536

### CODE REVIEW

**Comment by kevsmith** [comment]
Assigning bundles to groups chokes when the server return an error:

```
$ cogctl relay-groups assign test-group1 mist github-trigger
Assigned 'mist, github-trigger' to relay group `test-group1`
$ echo $?
0
$ cogctl relay-groups assign test-group1 mist github-trigger
** (Poison.SyntaxError) Unexpected token: <
    lib/poison/parser.ex:56: Poison.Parser.parse!/2
    lib/poison.ex:83: Poison.decode!/2
    lib/cog_api/http/api_response.ex:52: CogApi.HTTP.ApiResponse.parse_struct/2
    lib/cog_api/http/api_response.ex:31: CogApi.HTTP.ApiResponse.format/2
    (cogctl) lib/cogctl/actions/relay_groups/assign.ex:31: Cogctl.Actions.RelayGroups.Assign.do_assign/2
    (cogctl) lib/cogctl.ex:22: Cogctl.main/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
$ echo $?
1
```

**Comment by mpeck** [comment]
oh yeah, I saw that. I was thinking that it was because Cog was crashing. I was actually going to fix it there.

**Comment by kevsmith** [comment]
That too now that I look Cog's console. Would be nice if the server crapping itself didn't result cogctl following suit, though.

**Comment by mpeck** [comment]
Yeah, I agree. I'll look into handling server crashes more elegantly after I get this bug fixed.

**Pull request merged**
